# Generated by Django 4.0.3 on 2022-06-08 21:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(unique=True, upload_to=api.models.user_directory_path),
        ),
    ]
